[package]
name = "joinquote"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0", default-features = false, features = ["help"] }

[profile.release]
lto = true
strip = true
opt-level = "z"
